language: node_js  #设置语言
node_js: stable  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules #缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' #更改时区

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g   #生成

after_script:
  - git clone https://${GH_REF} .deploy_git  #GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   #这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "zhouhengheng0705"  #修改name
  - git config user.email "zhouhengheng99@gmail.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  #提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - master  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   GH_REF: github.com/zhouhengheng0705/zhouhengheng0705.github.io.git  #设置GH_REF，注意更改yourname
   secure: H3V9CshcZpdyd6KuHPAr8HPTsg1P6EU/bnI4Xho4bdqpkOhBEEdY35rI0bP4ieFn6DY1Y/wliQy+ZMO4gYT1WvahO43W3OEl4y3PunoUO4bXyPPNU2IWZe3KKRMjSVq1mN7zKF9LVfh0/NGiIupHRqMOnG8nHsvN/KhnczyDx66zh7QjrqB/ofSSGqAgy1yaPhsGoYoZSwk41zbxMfQ98gBfbrbJ3SfYUn7EqEBrL/PKsn6igDvCm2KdyB6k5XeDXipClJ6Zt/cfnWMIvtWN5EVr+QNloyaQm7AkgdhSb7B1bRXseDjiw0LicytMWoULhk435KzxzoWV/5x9Okf3HvibFA6rl6EOkzDZsY1yZ1bMd58fLaCxBbtLU/ssmd8uSPwYJH/uKTocjz0sMdMarQ1Ybwzq4ea5Qsy2hPpsfQmClO04aHL+oEhZdBY0UYZ/k0vJrbs9i7Zx4armwSLWtV9Q3gZlrRo54IqdGdd+HHRuKM3B9Fu9SImQKaOHDn6MELcyL0PLeKdXDc+LBzb8WPKS7qrbq6dGRfb89aK+jR7Df5H4y/zsQKtQ/nXqNt1nNQ/1YXFcldggjiKJuC6nq8/wMUmKKoJrZg3tPyljKmFBsoXT/US5rTL0g34eOYgtXN+QZuId1DkOnrbAarF6clKNGSdO1TJglyP2jfrKasU=

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - zhouhengheng99@gmail.com
  on_success: change
  on_failure: always
